apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "open-webui-calalang-net"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/jmcalalang/lab"
    path: services/open-webui-calalang-net
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
